server:
  port: 8089

service:
  name: ping-authentication-service
  static-base-path: ${SERVICE_STATIC_BASE_PATH}
  profile-images-path: ${SERVICE_PROFILE_IMAGES_PATH}
  static-ip-base: ${SERVICE_STATIC_IP_BASE}

spring:
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
  profiles:
    active: ${SPRING_PROFILES:development}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb

    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO} # update

jwt:
  secret: ${JWT_SECRET}
  issuer: ${JWT_ISSUER}

freeswitch:
  host: ${FREESWITCH_HOST}
