server:
  port: 8089

service:
  name: ping-authentication-service
  static-base-path: /home/${user.name}/application/${service.name}/files
  profile-images-path: ${service.static-base-path}/profiles

spring:
  servlet:
    multipart:
      max-request-size: 15MB
      max-file-size: 15MB
  profiles:
    active: development

  datasource:
    url: jdbc:mysql://localhost:3306/ping_db?useSSL=true&serverTimezone=UTC
    username: ping
    password: ping

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb

    hibernate:
      ddl-auto: create-drop

jwt:
  secret: ultraProductinReadySecretKey
  issuer: PingPlatform

freeswitch:
  host: 192.168.0.13
